# Check out https://docs.codemagic.io/yaml/building-a-native-ios-app/ for more information
# Please review and update values in curly braces

workflows:
    ios-app:
        name: iOS App
        environment:
            vars:
                XCODE_WORKSPACE: "OpenWeatherMap.xcodeproj"
                XCODE_SCHEME: "OpenWeatherMap"
            xcode: latest
            cocoapods: default
        scripts:
            - xcodebuild build -workspace OpenWeatherMap.xcodeproj -scheme "OpenWeatherMap" CODE_SIGN_IDENTITY="Apple Development" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        artifacts:
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
